local _, aFacts = ...

aFacts.dog = {
    "The Labrador Retriever has been on the AKC’s top 10 most popular breeds list for longer than any other breed.",
    "A dog’s nose print is unique, much like a person’s fingerprint.",
    "Forty-five percent of U.S. dogs sleep in their owner’s beds.",
    "All dogs dream, but puppies and senior dogs dream more frequently than adult dogs.",
    "Seventy percent of people sign their dog’s name on their holiday cards.",
    "A dog’s sense of smell is legendary, but did you know that their nose has as many as 300 million receptors? In comparison, a human nose has about 5 million.",
    "Rin Tin Tin, the famous German Shepherd Dog, was nominated for an Academy Award.",
    "Dogs’ noses can sense heat and thermal radiation, which explains why blind or deaf dogs can still hunt.",
    "The French Bulldog was first named the most popular breed in 2022.",
    "The name Collie, as in Border Collie, means “black.” (Collies once tended black-faced sheep.)",
    "Yawning is contagious — even for dogs. Research shows that the sound of a human yawn can trigger one from your dog. And it’s four times as likely to happen when it’s the yawn of a person your pet knows.",
    "The Dandie Dinmont Terrier is the only breed named for a fictional person, a character in the novel “Guy Mannering” by Sir Walter Scott.",
    "Dogs curl up in a ball when sleeping to protect their organs — a holdover from their days in the wild, when they were vulnerable to predator attacks.",
    "The Basenji dog breed is not technically “barkless,” as many people think. They can yodel.",
    "The Australian Shepherd dog breed is not actually from Australia. In fact, they are an American breed.",
    "The Labrador Retriever is originally from Newfoundland.",
    "Petting a dog can actually benefit your physical and mental health. Studies have shown that petting a dog for 15 minutes can lower blood pressure by 10%, can help lower feelings of stress, depression, and combat loneliness.",
    "There are over 75 million pet dogs in the U.S. — more than in any other country.",
    "A person who hunts with a Beagle is known as a “Beagler.”",
    "Dogs are not color-blind. They can see blue and yellow.",
    "All puppies are born deaf.",
    "Dalmatians are born completely white. They develop their spots as they get older.",
    "Dogs have about 1,700 taste buds. We humans have between 2,000 and 10,000.",
    "When dogs kick backward after they go to the bathroom, it’s not to cover it up, but to mark their territory, using the scent glands in their feet.",
    "A study shows that dogs are among a small group of animals who show voluntary unselfish kindness towards others without any reward.",
    "The Norwegian Lundehund is the only dog breed created for the job of puffin hunting.",
    "Greyhounds can beat cheetahs in a race. Cheetahs can only maintain that 70 mph speed for about thirty seconds. A Greyhound can maintain a 35 mph speed for about seven miles. The cheetah may start out first, but the Greyhound would soon overtake them.",
    "The Bloodhound’s sense of smell is so accurate that the results of its tracking can be used as evidence in a court of law.",
    "According to Guinness World Records, a Great Dane named Zeus is the world’s tallest male dog. Zeus is 3 feet, 5.18 inches tall.",
    "According to Guinness World Records, the shortest dog ever recorded was Pearl the Chihuahua. She measures 3.59 inches tall.",
    "Dog’s noses are wet to help them absorb scent chemicals! Their nose secretes a special mucus that helps to absorb these chemicals, and then they lick their noses to sample them, helping them understand what the smell is",
    "Newfoundland dogs are the ultimate doggy lifeguards, because they have water resistant coats and webbed feet. They were originally bred as fisherman’s helpers and to rescue people from drowning.",
    "Dogs have a sense of time. It's been proven that they know the difference between a hour and five. If conditioned to, they can predict future events, such as regular walk times.",
    "Your dog is as smart as a two-year old! Ever wonder why children around this age seem to have a special bond with the family dog? It could be because they speak the same language, roughly 250 words and gestures in fact.",
    "A study at UCSD claims that your dog can genuinely get jealous when they see you display affection for another creature.",
    "Dachshunds were originally bred to fight badgers.",
    "Stray dogs in Russia have learned how to ride the complex subway system, and get off at specific stops in search of food.",
    "Your dog can smell your feelings. In fact, your dog’s sense of smell is approximately 100,000 times better than yours. When a human is fearful, they perspire, and a dog is easily able to pick up on this change.",
    "Bluey, an Australian cattle dog, is recorded in the Guinness Book of World Records as the oldest dog to ever live. Bluey lived to be 29 years 5 months old and lived from 1910 to 1939.",
    "Dogs can be trained to to detect cancer and other diseases. Cancerous cells release different metabolic waste products than healthy cells in the human body. Dogs may even be able to sniff out cancer cells simply through smelling someone’s breath.",
    "Three dogs survived the historical sinking of the Titanic in 1912. Two Pomeranians and 1 Pekingese - all from First Class cabins.",
    "Do you have a dog that experiences separation anxiety? Try leaving some clothing with him that you’ve worn. It’s been proven that the scent you leave behind on your clothes can help ease your dog’s separation anxiety.",
    "When your dog is carefully choosing the perfect place to do his business, it is because they prefer to go poop in alignment with the Earth’s magnetic field.",
    "Dogs don’t sweat, instead they pant to cool themselves.",
    "Chocolate can be very deadly to dogs due to containing the ingredient, theobromine. Dogs cannot metabolize theobromine and ingesting chocolate could cause a severely toxic buildup in their system which could become fatal.",
    "Maltese dogs do not shed, making them perfect pups for people with allergies.",
    "There are more than 150 dog breeds, divided into 8 classes: sporting, hound, working, terrier, toy, non-sporting, herding, and miscellaneous.",
    "According to a recent survey, the most popular name for a dog is Max. Other popular names include Molly, Sam, Zach, and Maggie.",
    "Dogs can vary in size from a 36 inch (150+ lb.) Great Dane to a 2 lb. Chihuahua.",
    "Puppies and kittens can be adopted as early as 8 weeks of age.  Until then, they should stay with their moms and littermates.",
    "About 1/3 of the dogs that are surrendered to animal shelters are purebred dogs.",
    "Contrary to popular belief, dogs do not sweat by salivating. They sweat through the pads of their feet.",
    "An adult dog has 42 teeth.",
    "If a dog isn’t spayed or neutered, a female dog, her mate and their offspring can product 67,000 dogs in 6 years.",
    "The most successful mountain rescue dog ever was a St Bernard named Barry, who lived during the early 1800’s and saved 40 lives.",
    "Nearly all but two breeds of dogs have pink tongues: the Chow Chow and the Shar-pei both have black tongues.",
    "The Poodle haircut was originally meant to improve the dog’s swimming abilities as a retriever, with the pom-poms left in place to warm their joints.",
    "The top five favorite breeds of dogs in the US are: Labrador Retriever, Golden Retriever, German Shepherd, Beagle, and Dachshund.",
    "All dogs, regardless of breed, are direct descendants of wolves and technically of the same species.",
    "A dog’s whiskers — found on the muzzle, above the eyes and below the jaws — are technically known as vibrissae. They are touch-sensitive hairs than actually sense minute changes in airflow.",
    "Dogs are capable of locating the source of a sound in 6/100ths of a second by using their swiveling ears like radar dishes.",
    "Everything from the positioning of their ears to the muscles in them helps dogs pick up a bunchh of sounds that humans can’t hear. The most popular explanation for why dogs tilt their heads is that they’re trying to locate the source of a sound.",
    "Unspayed female dogs only go into heat twice a year, so dog breeders need to plan carefully.",
    "Some pet owners might notice the faint scent of corn chips or popcorn lingering around their dog. This is called “Frito feet,” and it happens when sweat and bacteria build up in the paws.",
    "You might expect your dog’s mouth to smell like, well, dog. But persistent bad breath can actually be a sign of dental disease or other health problems. If you don’t already, have your dog’s teeth examined by a veterinarian every year.",
    "It’s no secret: Dogs often eat their own feces (and other fecal matter too). But though it might be gross, the ASPCA says it’s perfectly normal, stemming from their pre-domestication days thousands of years ago.",
    "Dogs hating mailmen is nothing personal. Dogs are a protective species, and they understandably see a person coming near their house and placing unfamiliar objects in a box as a potential threat.",
    "Dogs yawn to calm themselves down, so repeated yawns could be a sign that your pup is feeling anxious or stressed out. Assessing the context of the situation can usually help you figure out what’s going on.",
    "Media portrayals of these furry frenemies would have you believe that chasing cats is hardwired in dogs’ DNA. But it’s not specific to cats; dogs’ evolutionary hunting instincts are the reason they chase after anything small and speedy.",
    "Dogs’ normal body temperature is slightly higher than that of humans (it hovers at around 101.5 degrees F), which means that hotter temperatures can affect them more. This is why you need to take care while walking your dog on a hot day."

}

--[[
Sources:
https://www.akc.org/expert-advice/lifestyle/dog-facts/
https://www.purina.co.uk/articles/dogs/behaviour/common-questions/amazing-dog-facts
https://www.thedrakecenter.com/services/dogs/blog/23-amazing-facts-about-dogs-you-probably-didnt-know
https://www.mspca.org/pet_resources/interesting-facts-about-dogs/
https://www.rd.com/list/dog-facts-you-didnt-know/
]]
