local _, aFacts = ...

aFacts.frog = {
    "There is evidence that frogs have roamed the Earth for more than 200 million years, at least as long as the dinosaurs.",
    "The world's largest frog is the goliath frog of West Africa—it can grow to 15 inches and weigh up to 7 pounds.",
    "One of the smallest frogs is the Cuban tree toad, which grows to half an inch long.",
    "While the life spans of frogs in the wild are unknown, frogs in captivity have been known to live more than 20 years.",
    "There are over 6,000 species of frogs worldwide. Scientists continue to search for new ones.",
    "Toads are frogs. The word 'toad' is usually used for frogs that have warty and dry skin, as well as shorter hind legs.",
    "Frogs have excellent night vision and are very sensitive to movement. The bulging eyes of most frogs allow them to see in front, to the sides, and partially behind them.",
    "When a frog swallows food, it pulls its eyes down into the roof of its mouth, to help push the food down its throat.",
    "Frogs were the first land animals with vocal cords. Male frogs have vocal sacs—pouches of skin that fill with air. These balloons resonate sounds like a megaphone, and some frog sounds can be heard from a mile away.",
    "Launched by their long legs, many frogs can leap more than 20 times their body length.",
    "The Costa Rican flying tree frog soars from branch to branch with the help of its feet. Webbing between the frog's fingers and toes extends out, helping the frog glide",
    "To blend into the environment, the Budgett's frog is muddy brown in color, while the Vietnamese mossy frog has spotty skin and bumps to make them look like little clumps of moss or lichen.",
    "Many poisonous frogs, such as the golden poison frog and dyeing poison frog, are boldly colored to warn predators of their dangerous toxic skins.",
    "Some colorful frogs, such as the Fort Randolph robber frog, have developed the same coloring as a coexisting poisonous species. Although their skins are not toxic, these mimics may gain protection from predators by looking dangerous.",
    "Like all amphibians, frogs are cold-blooded, meaning their body temperatures change with the temperature of their surroundings.",
    "When temperatures drop, some frogs dig burrows underground or in the mud at the bottom of ponds. They hibernate in these burrows until spring, completely still and scarcely breathing.",
    "The wood frog can live north of the Arctic Circle, surviving weeks with most of its body frozen. It uses glucose in its blood as a kind of antifreeze that concentrates in its organs, protecting them from damage while the rest of the body freezes solid.",
    "The Australian water-holding frog is a desert dweller that can wait up to seven years for rain. It burrows underground and surrounds itself in a transparent cocoon made of its own shed skin.",
    "Frogs are freshwater creatures, although some frogs such as the Florida leopard frog are able to live in brackish or nearly completely salt waters.",
    "Almost all frogs fertilize eggs outside of the female's body. The male holds the female around the waist in a mating hug called amplexus. Amplexus can last hours or days. One pair of toads stayed in amplexus for four months.",
    "The marsupial frog keeps her eggs in a pouch like a kangaroo. When the eggs hatch into tadpoles, she opens the pouch with her toes and spills them into the water.",
    "Pipa pipa, the Suriname toad of South America, carries her young embedded in the skin of her back. After mating, the eggs sink gradually into the female's back, and a skin pad forms over the eggs. The juvenile frogs then burst from her back.",
    "The gastric brooding frog of Australia swallows her fertilized eggs. The tadpoles remain in her stomach for up to eight weeks, finally hopping out of her mouth as little frogs. During the brooding period, her digestive system stops.",
    "Among Darwin frogs, it is the male who swallows and stores the developing tadpoles in his vocal sac until juvenile frogs emerge.",
    "Over 5,000 different frog species live in temperate and tropical habitats worldwide, but all share the same basic shape, with large hind legs that are excellent for jumping, swimming and digging.",
    "Unlike other amphibians, adult frogs have no tails. Instead, they have large hind legs, wide mouths, protruding eyes and damp skin through which they can absorb oxygen.",
    "Depending on where in the world you live, the terms frogs and toads are used differently. Generally, frogs are much faster, have smooth skin and spend most of their time in the water. Toads are slower, have rough skin and often burrow into the ground.",
    "Amphibians are cold-blooded. They have permeable skin, so they must find damp places to live to prevent them from drying out. As such, frogs thrive in freshwater habitats. Some spend their whole lives in water, while others only visit water to breed.",
    "Many species of frogs in the humid rainforests live high in the trees, safely away from ground-dwelling predators.",
    "Frogs inhabit every continent except Antarctica.",
    "Frog larvae, known as tadpoles, feed mostly on plant material, but adult frogs are carnivores.",
    "Depending on their size, frogs eat everything from insects and invertebrates to small mammals and other frogs! Frogs are ambush predators. They lie in wait to catch their prey, often with a spectacular jump!",
    "Frogs make a range of sounds, from the high-pitched squeaks of the squeaker frogs to the more traditional croaks of bullfrogs. They make noise for various reasons, such as to defend their territory or to warn other frogs when danger is near.",
    "Male frogs make noise to attract females, filling their vocal sacs with air and expelling it to make their calls.",
    "The loudest frog species in the world is the coqui, whose call has two parts – a low-frequency ‘co’ warning rival males to keep their distance and a high-pitched ‘qui’ to attract females.",
    "Frog species in tropical climates can reproduce several times at any point in the year, while those in high-latitude countries typically breed in early spring.",
    "Species like the common frog in the UK usually return to the pond where they themselves were spawned to breed",
    "Male frogs often attract females using sound, but some species, such as the Panamanian golden frog, use visual displays to impress females. This is one of the most endangered frog species.",
    "Female frogs can produce anything from one to 50,000 eggs, depending on the species.",
    "Some species carry eggs and tadpoles from one location to another to escape predators or reach a more advantageous environment. Perhaps one of the most interesting is Darwin’s frog – the males ingest the eggs and keep them safe in their vocal sacs.",
    "The process of changing from a tadpole to a frog is called metamorphosis. Tadpoles develop inside the eggs over a few weeks (depending on the species) and then hatch straight into the water.",
    "Tadpoles look like little commas with large heads and long tails. Over the next few months, tadpoles slowly develop legs and absorb their tail back into their bodies to save wasting nutrients. Their gills are replaced with air-breathing lungs.",
    "In some frog species, like the robber frogs of the Americas, eggs develop directly into small adults without a tadpole stage.",
    "Frogs have many natural predators, including birds such as herons, reptiles like snakes and alligators, mammals like otters, large fish and other frogs.",
    "Some of the biggest threats to frogs include habitat loss and the pollution of waterways. Frogs have very specific needs and have to be close to water sources. If they lose their habitat, they can struggle to find a new home.",
    "Frogs are vulnerable to climate change and unpredictable weather. For example, when they lay their frogspawn too early in unusually mild weather, sudden frosts and snow can kill the whole brood.",
    "One of the simplest ways to help frogs (and other species) in your own garden is to create a pond – the bigger, the better! Larger ponds are less likely to dry out in summer, but depth is the most important aspect to get right.",
    "Another thing you can do to help frogs is to respect their home. If visiting nature reserves, follow all instructions, particularly regarding protective measures such as washing your footwear before entering.",
    "Frogs use their long, sticky tongues to catch prey. The tongue flicks out of their mouths in a fraction of a second, effectively snagging their next meal.",
    "Frogs can breathe through their skin, their mouth, and their lungs, allowing them to survive in various conditions and adapt to their surroundings.",
    "Some frogs can leap up to 20 times their body length, which is like a human jumping 30 metres in a single bound.",
    "Frogs have excellent night vision and are primarily nocturnal, meaning they are most active during the night.",
    "Unlike humans, frogs don't drink water. Instead, they absorb it through their skin.",
    "Frogs have very strong and elongated hind legs, adapted for leaping and swimming.",
    "Some species of frogs can change colour based on temperature or their mood, effectively acting as living weather predictors.",
    "Sadly, more than one-third of all frog species are considered to be threatened with extinction.",
    "Frogs are considered a keystone species. They play crucial roles in the ecosystem and are used in human medicine for research and as a source of drugs.",
    "Some frog species, like the poison dart frog, have toxic secretions on their skin that can be harmful or even fatal to predators.",
    "Depending on the species, frogs can live for anywhere from a few years to several decades. The oldest recorded frog lived to be 40 years old.",
    "Some species of frogs migrate in large groups when the weather conditions are right. They can travel several miles to reach their breeding grounds.",
    "The Glass Frog is a unique species where the skin on their abdomen is transparent. This see-through feature allows you to glimpse into their internal organs, including the heart, liver, and gastrointestinal tract!",
    "Unlike birds or mammals, frogs lay eggs. These eggs are often laid in clusters in water and can number into the thousands for some species.",
    "Frogs have been to space! In 1970, NASA launched the first biological flight carrying a collection of bullfrogs. The mission aimed to understand more about the effects of space travel on human beings.",
    "The Kihansi spray toad is extinct in the wild. This fascinating species is one of the only frogs that give birth to live young. This means they are born as frogs and not tadpoles.",
}
--[[
Sources:
https://www.amnh.org/exhibitions/frogs-a-chorus-of-colors/frog-fun-facts
https://www.onekindplanet.org/animal/frog/
https://inamatchbox.com/blogs/news/21-fun-facts-you-wont-believe-about-frogs
https://www.wcs.org/get-involved/updates/5-fun-frog-facts
]]
