local _, aFacts = ...

aFacts.generic = {
    "The Pistol Shrimp is capable of snapping its claw shut so rapidly, that it creates a bubble which collapses to produce a sonic blast, louder than a sonic boom. Up to 230 decibels and 4400 degrees Celcius",
    "Flamingos are not pink. They are born grey, their diet of brine shrimp and blue green algae contains a natural pink dye called canthaxanthin that makes their feathers pink.",
    "Otters “hold hands” while sleeping, so they don’t float away from each other.",
    "Hummingbirds are the only known birds that can also fly backwards.",
    "Dolphins deliberately handle pufferfish causing them to release toxins as a defence mechanism. These toxins can be deadly in high doses, but also have a narcotic effect – and are a powerful hallucinogenic, which dolphins appear to enjoy.",
    "The Inland Taipan (also known as, the Western Taipan) is the most venomous snake in the world. A single bite contains enough venom to kill at least 100 fully grown men, and can kill within just 30 minutes, if left untreated.",
    "The worlds deadliest animal isn’t a shark, bear or tiger, but something far smaller – the mosquito. According to the WHO, 725,000 people are killed each year from mosquito-borne diseases, such as Malaria, dengue fever and yellow fever.",
    "Ants have colonised almost every landmass on Earth. Their population is estimated 20 quadrillion alone, in comparison to approx. 7 billion humans on the planet.",
    "The Mayfly reproduces and then dies, during that short 24hr period of life. Some species of Mayfly only live for 8-10 hours. Although they have the shortest adult lifespan, they actually exist as a nymph in water from 3-7 years.",
    "The horned lizard is able to shoot blood from its own eyes, up to a distance of 3 feet away. The rather bizarre and disgusting act is a defensive mechanism to confuse predators.",
    "Roosters prevent themselves from going deaf due to their own loud crowing, by tilting their head backs when they crow, which covers their ear canal completely, serving as a built-in ear-plug.",
    "Little is known about the elusive Giant squid, however the largest squid ever found measured over 50 feet and weighed nearly a tonne.",
    "The pangolin is able to roll up into an armour-plated ball, so lions can’t eat them.",
    "Koalas can sleep for up to 22 hours a day.",
    "Swifts spend most of their lives flying in the air, and can fly for almost an entire year, without ever landing.",
    "Even after having its head cut off, a cockroach can still live for weeks.",
    "A group of parrots is known as a pandemonium.",
    "The collective noun for porcupines, is a prickle.",
    "Cows poo up to 15 times a day, which can be as much as 115 pounds of manure per day, or approximately 21 tons per year.",
    "A common garden snail has 14,000 teeth. Their microscoptic teeth are called radula, and some species actually have over 20,000 teeth.",
    "A Blue Whales tongue can weigh as much as a car, or a small adult elephant.",
    "The longest living, verified animal is a Madagascar radiated tortoise, which died at an age of 188 years in May 1965.",
    "The fastest land animal on the planet is a cheetah. It can reach speeds of up to 75 mph (120 kph).",
    "While the Peregrine Falcon is the fastest bird, with a diving speed of 242 mph (389 kph). The fastest animal in horizontal flight is the brazilian free-tailed bat, which can reach speeds of 100mph.",
    "The sailfish and black marlin are joint fastest sea animals, and can swim up to 22 mph (36 kph).",
    "Baby elephants suck their trunks for comfort.",
    "The Nile crocodiles jaws can apply 5,000 pounds of pressure per square inch – the strongest bite of any animal in the world.",
    "Axolotl are able to regenerate lost limbs and body organs.",
    "The Giant Pacific Octopus has 3 hearts, 9 brains and blue blood. They are also able to change their colour and texture to camouflage themselves in a blink of an eye.",
    "A flea can jump distances 200 times their body length. They are able to jump 10 inches (25cm) vertically and up to 18 inches (45 cm) horizontally, making them one of the planets best jumpers relative to its size.",
    "The male seahorse goes through pregnancy and gives birth to babies. They are the only animal on earth where the male carries the baby rather than the female.",
    "Pufferfish can contain a tetrodoxin, a toxin that is up to 1,200 times more deadly than cyanide to humans. There is enough toxin in one pufferfish to kill 30 adult humans, and there is no known antidote.",
    "The loudest animal relative to size is the Water Boatman, which measures at just 12mm long, but can produce 99 dB of sound by rubbing its genitalia across its abdomen.",
    "The howler monkey is the loudest land animal. Its calls can be heard from 3 miles (5 km) away.",
    "There is an average of 50,000 spiders per acre in green areas.",
    "There’s over 45,000 known spider species, with the venom of a few only known to be dangerous to humans.",
    "The aptly named colossal squids eyes are as large as a basketball.",
    "White-tailed jackrabbits are the greatest land jumpers, having been recorded leaping an astonishing 21ft (6.4m) vertically.",
    "Grey-headed Albatross can circle the globe in only 46 days. The incredible round-the-world journey covers 14,000 miles over the 46 day period at a steady 13mph.",
    "Giraffes are the tallest land animal in the world, reaching heights of 19ft (5.8 m). The ostrich is the world’s tallest bird. It can grow up to 9 feet (2.7m) tall.",
    "An ostrich legs are so powerful that their kicks can kill a lion.",
    "The dementor wasp paralyses cockroaches with venom to its head, turning them into a zombie-like state. The toxins leave the cockroach unable to control its own movements, which incredibly makes it run into the wasps nest to meet its demise.",
    "More than half of all pigs in the world are kept by farmers in China. There are over 440 million pigs in China. United States in comparison has a mere 73 million pigs.",
    "Polar bears have jet black skin under their white fur coats. It helps them absorb heat to keep warm, while the white fur helps provides camouflage in the snowy and icy environment they live.",
    "Giant anteaters consume up to 35,000 ants and termites in a single day.",
    "The little known pangolin is the worlds most poached and trafficked animal due to the high demand of their scales and meat in Asian cultures. 70% of Chinese citizens believe pangolin products have medicinal value, when its been proven to be false.",
    "Great white sharks can detect a drop of blood in 25 gallons (100 litres) of water and can even sense tiny amounts of blood from 3 miles (5 km) away.",
    "The Naked Mole-Rat can live in an almost zero oxygen atmosphere. Incredibly, in a zero oxygen environment, the Naked Mole-Rat can still survive for up to 20-minutes without suffering any harm at all.",
    "The most venonmous fish in the world is the 30cm Stonefish. They have 13 sharp fin spines on their back, each with two venom glands. Their stings are extremely painful, can be lethal to humans, and mostly occur as a result of stepping on the creature.",
    "A study in the 90’s in the Serengeti found that 95% of cheetah cubs died before reaching adulthood. Many deaths were due to Lions, but also other predators and disease.",
    "A tigers rear legs are so powerful, that they have been found remaining to stand even after death.",
    "A Rhinoceros‘s horns are made of ‘keratin’, the same type of protein that makes up hair and fingernails.",
    "Some species of Rhinos have two horns, while others just have a single horn.",
    "The Alpine Swift is able to stay airborne for over 6 months without touching down. It holds the world record for the longest recorded uninterrupted flight by a bird, at over 200 days in the air as it hunted flying insects in the skies over West Africa.",
    "The Edible Dormouse (Glis glis) is able to hibernate the longest – up to 11-months of the year when food availability is low.",
    "Japanese Macaques play with snowballs for fun. These snow monkeys have been observed rolling up snowballs, then pushing them down hills just for the heck of it. Others gather lumps of snow in a ball and carry them around, proudly.",
    "Sperm whales are the world’s largest predator. They can be up to 20m long and weigh up to 80 tonnes.",
    "The largest insect to ever live was a “dragonfly” with a wingspan of over 75cm (2 and a half feet) across. They are called Meganeuropsis and were around 247 million years ago",
    "Koala’s have fingerprints almost identical to human. It is so hard to distinguish between the fingerprints of koalas and humans that even under a microscope it is hard to tell.",
    "Greenland sharks are the longest living vertebrates on earth, with one individual thought to be over 400 years old.",
    "Greenland sharks are giant, reaching up to 5m in length, and live in the cold deep waters of the North Atlantic. They are rarely seen, and little is known about them",
    "The blood ‘Dracula ant’ has the fastest recorded animal movement when it snaps its mandible. This cannibalistic ant can go from zero to 200mph in 0.000015 seconds when it snaps its mandibles.",
    "The box jellyfish is considered the most venomous marine species in the world.",
    "The Japanese Spider Crab has the longest leg span of any arthropod. From the tip of one claw to the other can be as long as almost 4m!",
    "Some albatrosses are lesbians. Albatrosses form bonds for life, returning to the same place every year to raise their young. Some of these bonds are between two females, with a study finding that in one breeding area 31% of pairs were two females.",
    "Some corvids (crows, rooks, ravens etc,) can understand physics. They can use tools, solve puzzles, recognise faces, and even understand physics.",
    "Sheep can recognise faces. As social animals, sheep are capable of recognising familiar and unfamiliar faces.",
    "Tardigrades can survive in space and go without eating for more than 10 years.",
    "Duck-billed platypus don’t have nipples, instead they concentrate milk to their belly and feed their young by sweating it out. The milk emerges from pores in the skin of the abdomen which the platypus puggles then lap up.",
    "Echidna’s are relatives of duck-billed platypuses and have a beak, spikes, a kangaroo-like pouch, and lays eggs. They are small at just 30–45cm and are known as spiny anteaters.",
    "Rabbits don’t have pads on their paws. Only fur. They are the only land mammals that do not have paw pads.",
    "The Yangtze giant softshell turtle is the biggest freshwater turtle in the world. It weighs between 150 to 220 kilograms (330 to 485 pounds) and is over 100cm (39in) in length",
    "Pea Crabs are miniature crabs that spend their whole lives inside oysters, clams, and mussels. Named because it is the size of a pea, this tiny crab relies entirely on its host for food.",
    "The Mariana snailfish is the deepest fish in the ocean, living up to around 8,000m below the surface. They live down in the deepest trenches of the ocean where they hunt invertebrates, such as crustaceans and shrimp.",
    "The shoebill stork can swallow baby crocodiles whole. These huge birds are over a meter tall (up to 5 feet) and have a wingspan of more than 2 m (almost 8 feet!)",
    "Lungfish are the only fish that have both lungs and gills. This allows them to survive when the water in their ponds/lakes dries up.",
    "Electric eels are in fact not eels, and give a shock strong enough to knock out a horse.",
    "The yellowhead jawfish incubates its eggs in its mouth. The male gathers up all of the eggs once they’ve been fertilised and stores them in his mouth until they hatch.",
    "The patu digua is thought to be this smallest spider in the world at just 0.37 mm. This Colombian spider is about one fifth the size of the head of a pin.",
    "Vampire bats share blood with their friends. Vampire bats need to eat blood at least every 48 hours to survive. Bats will share blood after a good meal with another bat that’s fed them in the past.",
    "The U.S. military trained bottlenose dolphins. Bottlenose dolphins were used in both the Vietnam and the Gulf to detect enemy swimmers trying to plant explosives on ships.",
    "Cuckoo birds hide their eggs in the nests of other species. The other bird species then raises the cuckoo chick as if it were its own, and the cuckoo mother doesn’t have to do any of the work.",
    "Elephants mourn their dead. Elephants will return to the place where family members died and stand in silence over the bones, sometimes bowing their heads.",
    "Meerkat parents train their offspring to hunt scorpions. They will bring back dead or almost dead scorpions back to the younger ones so that they can practice killing them without getting stung.",
    "Only 3-5% of mammals are monogamous.",
    "Gorilla’s have been seen dismantling traps set by poachers. Poaching is a big problem for gorillas, but young gorillas have learnt how to trap and dismantle snares.",
    "The earliest found depictions of dogs come from 8,000 years ago.",
    "Cats were domesticated 9,500 years ago in Ancient Egypt. They were worshiped in Ancient Egypt and some historians report that it was illegal to kill a cat.",
    "Emperor penguins are the world’s biggest penguins, and they trek 50–120 km (31–75 m) across the Antarctic to reach breeding colonies.",
    "Yaks are specially adapted to high altitudes, with a huge lung capacity and small red blood cells.",
    "Cuvier’s Beaked whales are one of the deepest diving mammals and can collapse their lungs to survive the high pressure.",
    "Orangutans are the heaviest tree-dwelling animals. There are three species of orangutan and adult males of all three typically weigh around 75kg (165lb) while females are ~37 kg (82 lb). They are ~1.5m(5ft) tall and have a huge arm span of ~2m (6ft)",
    "Chimpanzees are very intelligent and make all kinds of tools. For example, some use long sticks to fish out termites from their mounds. Other chimps have been recorded creating “spears” to hunt bushbabies!",
    "Shrike’s impale their prey on sticks to save them for later. Also known as “butcherbirds” they are famous for being fairly brutal songbirds.",
    "Vultures urinate and defecate on their own legs and feet to cool off on hot days. This a cooling mechanism called ‘urohydrosis’.",
    "Certain animals have anti-freeze proteins that allow them to survive extreme temperatures. These anti-freeze proteins prevent water in the cells of the animals from crystalising and forming ice.",
    "Honeypot ants have to be seen to be believed. During wet season, certain ants consume huge amounts of nectar, making their abdomens swell up to the size of a grape. During dry season, they provide the other ants with food by throwing it back up!",
    "Bees have 5 eyes. 2 at the front like a fly, and 3 smaller eyes like a spider. The three ‘ocelli’ eyes on the top of its head detect light, so the bee can sense if it’s being approached by a predator.",
    "Giant vampire bats lived 100,000 years ago and had a wingspan of 50cm (20 inches). These giant bats were roughly 30% larger than the modern vampire bats. The remains of one were recently found in a cave in Argentina.",
    "There are no ‘male’ Mourning geckos. They are an all female species, as they are ‘parthenogenetic’, meaning it can reproduce without males. Around 70 species in the world have shown this behaviour, including some crabs, snails and the Komodo dragon.",
    "There are an estimated 8.7 million species on earth and more than 80% of them are undiscovered"
}

--[[
Sources
https://factanimal.com/animal-facts/
]]
